### PR TITLE
Refactor Examples

### PR DESCRIPTION
**Pull request by PhilippvK**
~~Needs rebase after #44 is merged.~~

**Changes:**
- Add more example instructions (loads for RV32/RV64, XCV, ADDW,...)
- Run examples for `--riscv-xlen 32` and `--riscv-xlen 64`
- Run examples with/without `--no-extend`
- Use `llvm-lit` infrastructure for automated checks
- Parser: allow use of XLEN in casts and definitions
- Unify CoreDSL formatting

### CODE REVIEW

**Comment by PhilippvK** [comment]
@mathis-s I have the feeling that the support for immediates broke in an earlier commit ...

```
pattern-gen: /work/git/students/mathis/CoreDSL2LLVM/llvm/include/llvm/CodeGen/Register.h:111: llvm::MCRegister llvm::Register::asMCReg() const: Assertion `Reg == MCRegister::NoRegister || MCRegister::isPhysicalRegister(Reg)' failed.
```

**Comment by mathis-s** [comment]
> @mathis-s I have the feeling that the support for immediates broke in an earlier commit ...
> 
> ```
> pattern-gen: /work/git/students/mathis/CoreDSL2LLVM/llvm/include/llvm/CodeGen/Register.h:111: llvm::MCRegister llvm::Register::asMCReg() const: Assertion `Reg == MCRegister::NoRegister || MCRegister::isPhysicalRegister(Reg)' failed.
> ```

Will take a look!

**Comment by PhilippvK** [comment]
> > @mathis-s I have the feeling that the support for immediates broke in an earlier commit ...
> > ```
> > pattern-gen: /work/git/students/mathis/CoreDSL2LLVM/llvm/include/llvm/CodeGen/Register.h:111: llvm::MCRegister llvm::Register::asMCReg() const: Assertion `Reg == MCRegister::NoRegister || MCRegister::isPhysicalRegister(Reg)' failed.
> > ```
> 
> Will take a look!

Thanks. Here is the recent ci job: https://github.com/mathis-s/CoreDSL2LLVM/actions/runs/11251833148/job/31283706173?pr=45

**Comment by mathis-s** [comment]
Should be fixed. Problem was that LLVM had a useless COPY in the MIR. I added some code to peek through that copy.

The CV_ADDN instruction is a really tough in general though because we need an intermediate result larger than XLEN. Pretty nice that it manages to generate a pattern, though I'm not sure it would match.

**Comment by PhilippvK** [comment]
> Should be fixed. Problem was that LLVM had a useless COPY in the MIR. I added some code to peek through that copy.

Thanks, I just pushed a rebase.

> The CV_ADDN instruction is a really tough in general though because we need an intermediate result larger than XLEN. Pretty nice that it manages to generate a pattern, though I'm not sure it would match.

That was the reason why I added the test and run lit with and without the `--no-extend` flag.

**Review by mathis-s — APPROVED** [review]

**Pull request merged**
