### PR TITLE
XCV Updates

### PR DESCRIPTION
**Pull request by PhilippvK**
Needs to be rebased after #39 is merged.

TODO:
- [x] Let XCVsimd imply GPR32V

### CODE REVIEW

**Comment by PhilippvK** [comment]
@mathis-s Seems like the lint action is not allowed to comment here. Could you check the repository settings and tell me if the following options are enabled?
- Allow all actions and reusable workflows
- Read and write permissions

**Comment by mathis-s** [comment]
> @mathis-s Seems like the lint action is not allowed to comment here. Could you check the repository settings and tell me if the following options are enabled?
> 
>     * Allow all actions and reusable workflows
> 
>     * Read and write permissions

First one was enabled already, just enabled r/w permissions!

**Comment by PhilippvK** [comment]
@mathis-s still does not work for some reason. I even added `permissions: write-all` which should have hight priority than the repository settings...

```
  ERROR:CPP Linter:response returned 403 from POST https://api.github.com/repos/mathis-s/CoreDSL2LLVM/issues/40/comments with message: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/issues/comments#create-an-issue-comment","status":"403"}
  Traceback (most recent call last):
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/bin/cpp-linter", line 8, in <module>
      sys.exit(main())
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/__init__.py", line 81, in main
      rest_api_client.post_feedback(files=files, args=args)
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 239, in post_feedback
      self.update_comment(
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 335, in update_comment
      self.api_request(url=comments_url, method=req_meth, data=payload)
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/__init__.py", line 119, in api_request
      response.raise_for_status()
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/mathis-s/CoreDSL2LLVM/issues/40/comments
```

If I do a PR targerting my fork it works for some reason: https://github.com/PhilippvK/CoreDSL2LLVM/pull/5#issuecomment-2373351224

While the comment can not be posted, it is still available [here ](https://github.com/mathis-s/CoreDSL2LLVM/actions/runs/11072442947?pr=40#summary-30766666878) and we also have code annotations [here](https://github.com/mathis-s/CoreDSL2LLVM/pull/40/files).

**Comment by PhilippvK** [comment]
@mathis-s Would be worth a try to enable "Allow GitHub Actions to create and approve pull requests " as well. I recently enabled

```yml
tidy-review: true
format-review: true
```

which could be causing this problem.

**Comment by mathis-s** [comment]
> @mathis-s Would be worth a try to enable "Allow GitHub Actions to create and approve pull requests " as well. I recently enabled
> 
> ```yaml
> tidy-review: true
> format-review: true
> ```
> 
> which could be causing this problem.

Done!

**Comment by PhilippvK** [comment]
From my side this is good to merge after combining the ci and lint related commits.

**Review by mathis-s — APPROVED** [review]

**Pull request merged**
