### PR TITLE
Merge with LLVM v19.1.0

### PR DESCRIPTION
**Pull request by PhilippvK**
Do not merge yet as it is untested (waiting for CI results)

This PR seems to overwhelm GitHub a bit...

@mathis-s  Should we rather do a single sqashed commit instead? We would have a much cleaner history but maybe have some difficulties when merging/rebasing in the future... Another alternative would be to do a full rebase on latest LLVM, but that coudn't be submitted via a PR as it would require a new default branch or force pushing...

### CODE REVIEW

**Comment by PhilippvK** [comment]
There are still some fixes I need to port. I will remove the draft status once I have verified everything still works locally…

**Comment by mathis-s** [comment]
My go-to option would be force pushing a rebase, but no strong preference

**Comment by PhilippvK** [comment]
I can do that, if you don't mind the new commit dates and Author!=Committer...

**Comment by PhilippvK** [comment]
We could have a new branch `llvm-19.1.0` and make it the default branch. If we move to a new LLVM version we would still have the old branch for supporting older versions.

**Comment by mathis-s** [comment]
Sure, making a new default branch sounds good!

**Comment by PhilippvK** [comment]
@mathis-s can you push https://github.com/PhilippvK/CoreDSL2LLVM/tree/rebase_llvm19.1.0 to your repo then? (Probably rename branch to `llvm-19.1.0` first)

CI just finished successfully: https://github.com/PhilippvK/CoreDSL2LLVM/actions/runs/11026221848

**Comment by mathis-s** [comment]
Pushed!

**Comment by PhilippvK** [comment]
Great, I will prepare some PRs for my patches soon!

**Pull request closed without merging**
